/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monapp;

import static BDD.Configuration.*;
import Model.Colors;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ali Abdoulkader Ali
 */
public class Conges extends javax.swing.JFrame {

    String SQL, table = "employe", nomEmp, prenomEmp, dateEmbaucheEmp, typeContratEmp, posteEmp, Conge, dateDebutConge, dateFinConge;
    String colonnes = "num_cni, nom, prenom, date_embauche, contrat, poste, debut_conge, fin_conge, type_conge";
    ResultSet res;

    /**
     * Creates new form Conges
     */
    public Conges() {
        initComponents();
        supprimer.setEnabled(false);
        modifier.setEnabled(false);
        top.setBackground(Colors.INSTANCE.secondaryColor());
        setLocationRelativeTo(null);
        setBackground(Colors.INSTANCE.secondaryColor());
        body.setBackground(Colors.INSTANCE.secondaryColor());
        bottom.setBackground(Colors.INSTANCE.secondaryColor());
        top.setBackground(Colors.INSTANCE.primaryColor());

        tableConge();
    }

    public void tableConge() {
        String[] colonnes = {"num_cni", "nom", "prenom", "date_embauche", "contrat", "poste", "debut_conge", "fin_conge", "type_conge"};

        res = select(colonnes, table);
        maTable.setModel(DbUtils.resultSetToTableModel(res));
    }

    public void actualiser() {
        nom.setText("");
        prenom.setText("");
        dateEmb.setCalendar(null);
        typeContrat.setSelectedIndex(0);
        poste.setText("");
        typeConge.setSelectedIndex(0);
        debutConge.setCalendar(null);
        finConge.setCalendar(null);
        supprimer.setEnabled(false);
        modifier.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        bottom = new javax.swing.JPanel();
        infoperso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        poste = new javax.swing.JTextField();
        dateEmb = new com.toedter.calendar.JDateChooser();
        typeContrat = new javax.swing.JComboBox<>();
        infoEmploi = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        debutConge = new com.toedter.calendar.JDateChooser();
        finConge = new com.toedter.calendar.JDateChooser();
        typeConge = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        operations = new javax.swing.JPanel();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        maTable = new javax.swing.JTable();
        recherche = new javax.swing.JPanel();
        rech_poste = new javax.swing.JTextField();
        rech_nom = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body.setPreferredSize(new java.awt.Dimension(1300, 700));

        jLabel1.setBackground(new java.awt.Color(236, 204, 104));
        jLabel1.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 204, 104));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-vacation-64.png"))); // NOI18N
        jLabel1.setText("Gestion des Congés");
        jLabel1.setToolTipText("");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-48.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(441, 441, 441)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(topLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(back)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        infoperso.setBackground(Colors.INSTANCE.secondaryColor());
        infoperso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations Personnelles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(Colors.INSTANCE.textColor());
        jLabel2.setText("Nom :");

        nom.setEditable(false);
        nom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(Colors.INSTANCE.textColor()
        );
        jLabel3.setText("Prénom :");

        prenom.setEditable(false);
        prenom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(Colors.INSTANCE.textColor());
        jLabel5.setText("Date d'Embauche :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(Colors.INSTANCE.textColor());
        jLabel8.setText("Type Contrat");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setForeground(Colors.INSTANCE.textColor());
        jLabel16.setText("Poste :");

        poste.setEditable(false);
        poste.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        dateEmb.setEnabled(false);

        typeContrat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir ...", "Contrat à Durée Déterminé (CDD)", "Contrat à Durée Indéterminé (CDI)" }));
        typeContrat.setEnabled(false);

        javax.swing.GroupLayout infopersoLayout = new javax.swing.GroupLayout(infoperso);
        infoperso.setLayout(infopersoLayout);
        infopersoLayout.setHorizontalGroup(
            infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopersoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeContrat, 0, 1, Short.MAX_VALUE)
                    .addComponent(nom)
                    .addComponent(prenom)
                    .addComponent(dateEmb, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(poste)))
        );
        infopersoLayout.setVerticalGroup(
            infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopersoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateEmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(typeContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(poste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoEmploi.setBackground(Colors.INSTANCE.secondaryColor());
        infoEmploi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations sur le congé", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(Colors.INSTANCE.textColor());
        jLabel10.setText("Date Début Congé :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(Colors.INSTANCE.textColor());
        jLabel12.setText("Date Fin Congé :");

        typeConge.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir ...", "congé payé", "congé maladie", "congé maternité", "congé paternité", "congé sans solde" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(Colors.INSTANCE.textColor());
        jLabel9.setText("Type Congé :");

        javax.swing.GroupLayout infoEmploiLayout = new javax.swing.GroupLayout(infoEmploi);
        infoEmploi.setLayout(infoEmploiLayout);
        infoEmploiLayout.setHorizontalGroup(
            infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEmploiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(typeConge, 0, 217, Short.MAX_VALUE)
                    .addComponent(debutConge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(finConge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        infoEmploiLayout.setVerticalGroup(
            infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEmploiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(debutConge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(finConge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(typeConge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        operations.setBackground(Colors.INSTANCE.primaryColor());
        operations.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opérations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-close-20.png"))); // NOI18N
        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-20.png"))); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-20.png"))); // NOI18N
        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout operationsLayout = new javax.swing.GroupLayout(operations);
        operations.setLayout(operationsLayout);
        operationsLayout.setHorizontalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifier)
                .addGap(34, 34, 34)
                .addComponent(supprimer)
                .addGap(32, 32, 32)
                .addComponent(annuler)
                .addGap(120, 120, 120))
        );
        operationsLayout.setVerticalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsLayout.createSequentialGroup()
                .addGroup(operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifier)
                    .addComponent(supprimer)
                    .addComponent(annuler))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        maTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° CNI", "Nom", "Prenom", "Date Embauche", "Contrat", "Poste", "Debut Congé", "Fin Congé", "type congé"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        maTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maTableMouseClicked(evt);
            }
        });
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();
        jScrollPane1.setViewportView(maTable);

        recherche.setBackground(Colors.INSTANCE.primaryColor());
        recherche.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recherche", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        rech_poste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rech_posteKeyReleased(evt);
            }
        });

        rech_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rech_nomKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setForeground(Colors.INSTANCE.textColor());
        jLabel17.setText("Nom :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setForeground(Colors.INSTANCE.textColor());
        jLabel18.setText("Poste :");

        javax.swing.GroupLayout rechercheLayout = new javax.swing.GroupLayout(recherche);
        recherche.setLayout(rechercheLayout);
        rechercheLayout.setHorizontalGroup(
            rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rechercheLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rech_poste, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rech_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        rechercheLayout.setVerticalGroup(
            rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rechercheLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rech_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rech_poste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addComponent(infoperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bottomLayout.createSequentialGroup()
                                .addComponent(infoEmploi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoEmploi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(infoperso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        copyright.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 204, 102));
        copyright.setText("Copyright © 2021 | Ali Abdoulkader Ali - Helem Houmed - Aboubaker Ainan| All rights reserved");

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(copyright)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyright)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 1346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.dispose();
        new Bienvenue().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();

        recuperation();

        String[] colonnes = {"nom", "prenom", "date_embauche", "contrat", "poste", "debut_conge", "fin_conge", "type_conge"};

        String[] valeurs = {nomEmp, prenomEmp, dateEmbaucheEmp, typeContratEmp, posteEmp,
            dateDebutConge, dateFinConge, Conge};

        String cni = String.valueOf(model.getValueAt(maTable.getSelectedRow(), 0));
        try {
            if (debutConge.getDate().after(dateEmb.getDate())) {
                if (finConge.getDate().after(debutConge.getDate())) {

                    updateTable(table, colonnes, valeurs, cni);

                } else {
                    JOptionPane.showMessageDialog(this, "La date de fin du congé doit être supérieur à la date de début du congé");
                }
            } else {
                JOptionPane.showMessageDialog(this, "La date de début congé doit être supérieur à la date d'embauche");
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("");
        }

        actualiser();
        tableConge();
    }//GEN-LAST:event_modifierActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();
        int ligne = maTable.getSelectedRow();
        String cni = String.valueOf(model.getValueAt(ligne, 0));
        if (maTable.getSelectedRowCount() == 1) {
            supprimer.setEnabled(true);
            deleteColumn(table, cni);

            if (maTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table vide !");
            }
        } else {
            supprimer.setEnabled(true);
        }

        actualiser();
        tableConge();
    }//GEN-LAST:event_supprimerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        actualiser();
    }//GEN-LAST:event_annulerActionPerformed

    private void maTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();

        int selectedRowIndex = maTable.getSelectedRow();
        Date date = null, date1 = null, date2 = null;
        supprimer.setEnabled(true);
        modifier.setEnabled(true);
        try {

            nom.setText(model.getValueAt(selectedRowIndex, 1).toString());
            prenom.setText(model.getValueAt(selectedRowIndex, 2).toString());
            date = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRowIndex, 3));
            dateEmb.setDate(date);
            typeContrat.setSelectedItem(model.getValueAt(selectedRowIndex, 4));
            poste.setText(model.getValueAt(selectedRowIndex, 5).toString());
            date1 = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRowIndex, 6));
            debutConge.setDate(date1);
            date2 = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRowIndex, 7));
            finConge.setDate(date2);
            typeConge.setSelectedItem(model.getValueAt(selectedRowIndex, 8).toString());
        } catch (ParseException ex) {
            System.out.println("");
        } catch (NullPointerException e) {
            System.out.println("");
        }

    }//GEN-LAST:event_maTableMouseClicked

    private void rech_posteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rech_posteKeyReleased
        String poste = rech_poste.getText();
        maTable.setModel(DbUtils.resultSetToTableModel(searchByJob(table, colonnes, poste)));
    }//GEN-LAST:event_rech_posteKeyReleased

    private void rech_nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rech_nomKeyReleased
        String nom = rech_nom.getText();
        maTable.setModel(DbUtils.resultSetToTableModel(searchByName(table, colonnes, nom)));
    }//GEN-LAST:event_rech_nomKeyReleased

    public void recuperation() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String daterecup = sdf.format(dateEmb.getDate());
            String daterecup1 = sdf.format(debutConge.getDate());
            String daterecup2 = sdf.format(finConge.getDate());

            nomEmp = nom.getText().toUpperCase().trim();
            prenomEmp = prenom.getText();
            dateEmbaucheEmp = daterecup;
            typeContratEmp = typeContrat.getSelectedItem().toString();
            posteEmp = poste.getText();
            Conge = typeConge.getSelectedItem().toString();
            dateDebutConge = daterecup1;
            dateFinConge = daterecup2;
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Saisissez bien les dates !");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conges.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conges().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JLabel back;
    private javax.swing.JPanel body;
    private javax.swing.JPanel bottom;
    private javax.swing.JLabel copyright;
    private com.toedter.calendar.JDateChooser dateEmb;
    private com.toedter.calendar.JDateChooser debutConge;
    private com.toedter.calendar.JDateChooser finConge;
    private javax.swing.JPanel infoEmploi;
    private javax.swing.JPanel infoperso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable maTable;
    private javax.swing.JButton modifier;
    private javax.swing.JTextField nom;
    private javax.swing.JPanel operations;
    private javax.swing.JTextField poste;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField rech_nom;
    private javax.swing.JTextField rech_poste;
    private javax.swing.JPanel recherche;
    private javax.swing.JButton supprimer;
    private javax.swing.JPanel top;
    private javax.swing.JComboBox<String> typeConge;
    private javax.swing.JComboBox<String> typeContrat;
    // End of variables declaration//GEN-END:variables
}
