/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monapp;

import Model.*;
import static BDD.Configuration.*;
import static Model.Country.*;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ali Abdoulkader Ali
 */

public class Employe extends javax.swing.JFrame {

    ResultSet res, rd;
    String SQL, table = "employe",colonnes ="num_cni,prenom,nom,sexe,dateNais,lieuNais,grpsanguin,etude,departement,poste,contrat,salaire,telMobile,telFixe,email";
    String num_cni, nomEmp, prenomEmp, sexeEmp, dateNaissanceEmp, lieuNaissanceEmp, grpSanguinEmp, etudeEmp, departementEmp, posteEmp, typeContratEmp, telMobileEmp, telFixeEmp, emailEmp, salaireEmp, embauche;
    Country[] listCountry = createCountryList();
    //private static final String PATTERN = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";

    /**
     * Creates new form Employe
     */
    public Employe() {
        initComponents();
        supprimer.setEnabled(false);
        top.setBackground(Colors.INSTANCE.secondaryColor());
        setLocationRelativeTo(null);
        setBackground(Colors.INSTANCE.secondaryColor());
        body.setBackground(Colors.INSTANCE.secondaryColor());
        bottom.setBackground(Colors.INSTANCE.secondaryColor());
        top.setBackground(Colors.INSTANCE.primaryColor());
        cni.setFont(new java.awt.Font("Tahoma", 1, 13));

        table();

    }

    public void table() {

        String[] colonnes = {"num_cni", "prenom","nom", "sexe", "dateNais", "lieuNais", "grpsanguin", "etude", "departement", "poste",
            "contrat", "salaire", "date_embauche", "telMobile", "telFixe", "email"};

        res = select(colonnes, "employe");
        
        maTable.setModel(DbUtils.resultSetToTableModel(res));
        ajouter.setEnabled(true);

    }

    public void actualiser() {
        prenom.setText("");
        nom.setText("");
        cni.setText("");
        sexe.setSelectedIndex(0);
        dateNaissance.setCalendar(null);
        lieuNaissance.setSelectedIndex(0);
        groupeSanguin.setSelectedIndex(0);
        niveauEtude.setSelectedIndex(0);
        departement.setText("");
        poste.setText("");
        typeContrat.setSelectedIndex(0);
        salaire.setText("");
        telMobile.setText("");
        telFixe.setText("");
        email.setText("");
        dateEmbauche.setCalendar(null);
        supprimer.setEnabled(false);
        ajouter.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        bottom = new javax.swing.JPanel();
        infoperso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateNaissance = new com.toedter.calendar.JDateChooser();
        sexe = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        groupeSanguin = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        niveauEtude = new javax.swing.JComboBox<>();
        lieuNaissance = new javax.swing.JComboBox<>();
        lieuNaissance = new javax.swing.JComboBox<Country>(listCountry);
        jLabel16 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        cni = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        infoEmploi = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        typeContrat = new javax.swing.JComboBox<>();
        departement = new javax.swing.JTextField();
        poste = new javax.swing.JTextField();
        salaire = new javax.swing.JTextField();
        dateEmbauche = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        contact = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        telMobile = new javax.swing.JFormattedTextField();
        telFixe = new javax.swing.JFormattedTextField();
        email = new javax.swing.JTextField();
        operations = new javax.swing.JPanel();
        ajouter = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        maTable = new javax.swing.JTable();
        vider = new javax.swing.JButton();
        recherche = new javax.swing.JPanel();
        rech_poste = new javax.swing.JTextField();
        rech_nom = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(236, 204, 104));
        jLabel1.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 204, 104));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-employee-64.png"))); // NOI18N
        jLabel1.setText(" Gestion des Employés");
        jLabel1.setToolTipText("");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-48.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(446, 446, 446)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(topLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(back)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        bottom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Détails sur l'employé", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        infoperso.setBackground(Colors.INSTANCE.secondaryColor());
        infoperso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations Personnelles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(Colors.INSTANCE.textColor());
        jLabel2.setText("Prénom :");

        prenom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(Colors.INSTANCE.textColor()
        );
        jLabel3.setText("N° CNI :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(Colors.INSTANCE.textColor());
        jLabel4.setText("Sexe :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(Colors.INSTANCE.textColor());
        jLabel5.setText("Date De Naissance :");

        sexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir ...", "Masculin", "Féminin" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(Colors.INSTANCE.textColor());
        jLabel6.setText("Lieu De Naissance :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(Colors.INSTANCE.textColor());
        jLabel7.setText("Groupe Sanguin :");

        groupeSanguin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir ...", "A+", "A-", "AB+", "AB-", "O+", "O-" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(Colors.INSTANCE.textColor());
        jLabel8.setText("Niveau D'Etude :");

        niveauEtude.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir ...", "Baccalauréat Générale", "Bac Pro", "Licence", "Master", "Doctorat", "Autre" }));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setForeground(Colors.INSTANCE.textColor()
        );
        jLabel16.setText("Nom :");

        nom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        try {
            cni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setText("6 chiffres");

        javax.swing.GroupLayout infopersoLayout = new javax.swing.GroupLayout(infoperso);
        infoperso.setLayout(infopersoLayout);
        infopersoLayout.setHorizontalGroup(
            infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopersoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addGroup(infopersoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19))
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom)
                    .addComponent(niveauEtude, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(groupeSanguin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prenom)
                    .addComponent(sexe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateNaissance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lieuNaissance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cni)))
        );
        infopersoLayout.setVerticalGroup(
            infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopersoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lieuNaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(groupeSanguin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(niveauEtude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        infoEmploi.setBackground(Colors.INSTANCE.secondaryColor());
        infoEmploi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations sur l'Emploi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(Colors.INSTANCE.textColor());
        jLabel9.setText("Departement :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(Colors.INSTANCE.textColor());
        jLabel10.setText("Poste :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setForeground(Colors.INSTANCE.textColor());
        jLabel11.setText("Type du Contrat :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(Colors.INSTANCE.textColor());
        jLabel12.setText("Salaire :");

        typeContrat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir ...", "Contrat à Durée Déterminé (CDD)", "Contrat à Durée Indéterminé (CDI)" }));

        departement.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        poste.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        salaire.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        salaire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salaireKeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setForeground(Colors.INSTANCE.textColor());
        jLabel20.setText("Date d'embauche :");

        javax.swing.GroupLayout infoEmploiLayout = new javax.swing.GroupLayout(infoEmploi);
        infoEmploi.setLayout(infoEmploiLayout);
        infoEmploiLayout.setHorizontalGroup(
            infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEmploiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel12)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10))
                    .addComponent(jLabel20))
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoEmploiLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(departement)
                            .addComponent(poste)
                            .addComponent(typeContrat, 0, 230, Short.MAX_VALUE)
                            .addComponent(salaire)))
                    .addGroup(infoEmploiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateEmbauche, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        infoEmploiLayout.setVerticalGroup(
            infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEmploiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(departement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(poste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(typeContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(salaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(dateEmbauche, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        contact.setBackground(Colors.INSTANCE.secondaryColor());
        contact.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setForeground(Colors.INSTANCE.textColor());
        jLabel13.setText("Tél. Mobile :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setForeground(Colors.INSTANCE.textColor());
        jLabel14.setText("Tél. Fixe :");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setForeground(Colors.INSTANCE.textColor());
        jLabel15.setText("E-Mail :");

        try {
            telMobile.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+253) 77 ## ## ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telMobile.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        try {
            telFixe.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(+253) ## ## ## ##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telFixe.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        email.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        javax.swing.GroupLayout contactLayout = new javax.swing.GroupLayout(contact);
        contact.setLayout(contactLayout);
        contactLayout.setHorizontalGroup(
            contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(33, 33, 33)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email)
                    .addGroup(contactLayout.createSequentialGroup()
                        .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(telMobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(telFixe, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 102, Short.MAX_VALUE)))
                .addContainerGap())
        );
        contactLayout.setVerticalGroup(
            contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contactLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(telMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telFixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(10, 10, 10)
                .addGroup(contactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        operations.setBackground(Colors.INSTANCE.primaryColor());
        operations.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opérations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-20.png"))); // NOI18N
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-close-20.png"))); // NOI18N
        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-20.png"))); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-20.png"))); // NOI18N
        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout operationsLayout = new javax.swing.GroupLayout(operations);
        operations.setLayout(operationsLayout);
        operationsLayout.setHorizontalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(ajouter)
                .addGap(34, 34, 34)
                .addComponent(modifier)
                .addGap(34, 34, 34)
                .addComponent(supprimer)
                .addGap(32, 32, 32)
                .addComponent(annuler)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        operationsLayout.setVerticalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ajouter)
                    .addComponent(modifier)
                    .addComponent(supprimer)
                    .addComponent(annuler))
                .addContainerGap())
        );

        maTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° CNI", "Nom", "Prenom", "Sexe", "DateNais", "Lieu de Naissance", "Groupe Sanguin", "Niveau Etude", "Département", "Poste", "Type du Contrat", "Salaire", "dateEmbauche", "Tél Mobile", "Tél Fixe", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        maTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(maTable);

        vider.setText("Vider la table");
        vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderActionPerformed(evt);
            }
        });

        recherche.setBackground(Colors.INSTANCE.primaryColor());
        recherche.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recherche", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        rech_poste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rech_posteKeyReleased(evt);
            }
        });

        rech_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rech_nomKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setForeground(Colors.INSTANCE.textColor());
        jLabel17.setText("Nom :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setForeground(Colors.INSTANCE.textColor());
        jLabel18.setText("Poste :");

        javax.swing.GroupLayout rechercheLayout = new javax.swing.GroupLayout(recherche);
        recherche.setLayout(rechercheLayout);
        rechercheLayout.setHorizontalGroup(
            rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rechercheLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rech_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(37, 37, 37)
                .addComponent(rech_poste, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rechercheLayout.setVerticalGroup(
            rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rechercheLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rech_poste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rech_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addComponent(infoperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(infoEmploi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bottomLayout.createSequentialGroup()
                                .addGap(311, 311, 311)
                                .addComponent(vider, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bottomLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(vider))
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addComponent(infoEmploi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(infoperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
        );

        copyright.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 204, 102));
        copyright.setText("Copyright © 2021 | Ali Abdoulkader Ali - Helem Houmed - Aboubaker Ainan| All rights reserved");

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(copyright)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bodyLayout.createSequentialGroup()
                        .addComponent(bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.dispose();
        new Bienvenue().setVisible(true);

    }//GEN-LAST:event_backMouseClicked

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed

        recuperation();

        String[] colonnes = {"nom", "prenom", "num_cni", "sexe", "dateNais", "lieuNais", "grpsanguin", "etude", "departement", "poste", "contrat", "salaire", "date_embauche", "telMobile", "telFixe", "email"};
        String[] values = {nomEmp, prenomEmp, num_cni, sexeEmp, dateNaissanceEmp, lieuNaissanceEmp, grpSanguinEmp, etudeEmp, departementEmp,
            posteEmp, typeContratEmp, salaireEmp, embauche, telMobileEmp, telFixeEmp, emailEmp};
        res = selectCondition(table, num_cni);

        if (!nomEmp.isEmpty() && !prenomEmp.equals("") && !num_cni.equals("") && sexe.getSelectedIndex() != 0 && !dateNaissanceEmp.equals("")
                && !posteEmp.equals("") && !telMobileEmp.equals("") && !salaireEmp.equals("") && !emailEmp.equals("")
                && lieuNaissance.getSelectedIndex() != 0 && groupeSanguin.getSelectedIndex() != 0 && niveauEtude.getSelectedIndex() != 0 && !departementEmp.equals("")
                && typeContrat.getSelectedIndex() != 0 && !telFixeEmp.equals("") && !embauche.equals("")) {

            if (dateEmbauche.getDate().after(dateNaissance.getDate())) {
                insert("employe", colonnes, values);
                System.out.println("employé ajouté");
            }else{
                JOptionPane.showMessageDialog(this, "La date d'embauche doit ête supérieur à la date de naissance !!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !");
        }
        actualiser();
        table();
    }//GEN-LAST:event_ajouterActionPerformed

    private void salaireKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaireKeyPressed
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            salaire.setEditable(false);
        } else {
            salaire.setEditable(true);
        }
    }//GEN-LAST:event_salaireKeyPressed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();

        recuperation();

        String[] colonnes = {"num_cni", "prenom","nom", "sexe", "dateNais", "lieuNais", "grpsanguin", "etude", "departement", "poste", "contrat", "salaire", "date_embauche", "telMobile", "telFixe", "email"};

        String[] valeurs = {num_cni,prenomEmp,nomEmp, sexeEmp, dateNaissanceEmp, lieuNaissanceEmp, grpSanguinEmp, etudeEmp, departementEmp,
            posteEmp, typeContratEmp, salaireEmp, embauche, telMobileEmp, telFixeEmp, emailEmp};

        String cni = String.valueOf(model.getValueAt(maTable.getSelectedRow(), 0));

        updateTable(table, colonnes, valeurs, cni);

        actualiser();
        table();

    }//GEN-LAST:event_modifierActionPerformed

    private void maTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();

        int selectedRowIndex = maTable.getSelectedRow();
        Date date = null, date1 = null;
        try {
            date = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRowIndex, 4));
            date1 = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRowIndex, 12));
            cni.setText(model.getValueAt(selectedRowIndex, 0).toString());
            prenom.setText(model.getValueAt(selectedRowIndex, 1).toString());
            nom.setText(model.getValueAt(selectedRowIndex, 2).toString());
            sexe.setSelectedItem(model.getValueAt(selectedRowIndex, 3).toString());
            dateNaissance.setDate(date);
            lieuNaissance.setSelectedItem(model.getValueAt(selectedRowIndex, 5).toString());
            groupeSanguin.setSelectedItem(model.getValueAt(selectedRowIndex, 6).toString());
            niveauEtude.setSelectedItem(model.getValueAt(selectedRowIndex, 7).toString());
            departement.setText(model.getValueAt(selectedRowIndex, 8).toString());
            poste.setText(model.getValueAt(selectedRowIndex, 9).toString());
            typeContrat.setSelectedItem(model.getValueAt(selectedRowIndex, 10).toString());
            salaire.setText(model.getValueAt(selectedRowIndex, 11).toString());
            dateEmbauche.setDate(date1);
            telMobile.setText(model.getValueAt(selectedRowIndex, 13).toString());
            telFixe.setText(model.getValueAt(selectedRowIndex, 14).toString());
            email.setText(model.getValueAt(selectedRowIndex, 15).toString());
            ajouter.setEnabled(false);
            supprimer.setEnabled(true);
        } catch (ParseException ex) {
            Logger.getLogger(Employe.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_maTableMouseClicked

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        actualiser();
    }//GEN-LAST:event_annulerActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();
        int ligne = maTable.getSelectedRow();
        String cni = String.valueOf(model.getValueAt(ligne, 0));
        if (maTable.getSelectedRowCount() == 1) {
            supprimer.setEnabled(true);
            deleteColumn(table, cni);

            if (maTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table vide !");
            }
        } else {
            supprimer.setEnabled(true);
        }

        actualiser();
        table();
    }//GEN-LAST:event_supprimerActionPerformed

    private void viderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderActionPerformed
        dbConn();
        SQL = "TRUNCATE TABLE " + table;
        executionUpdate(SQL);
        table();
    }//GEN-LAST:event_viderActionPerformed


    private void rech_nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rech_nomKeyReleased
        String nom = rech_nom.getText();
        maTable.setModel(DbUtils.resultSetToTableModel(searchByName(table,colonnes,nom)));
    }//GEN-LAST:event_rech_nomKeyReleased

    private void rech_posteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rech_posteKeyReleased
        String poste = rech_poste.getText();
        maTable.setModel(DbUtils.resultSetToTableModel(searchByJob(table, colonnes, poste)));
    }//GEN-LAST:event_rech_posteKeyReleased

    public void recuperation() {
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String daterecup = sdf.format(dateNaissance.getDate());
            String daterecup1 = sdf.format(dateEmbauche.getDate());
            Country selectedCountry = (Country) lieuNaissance.getSelectedItem();

            nomEmp = nom.getText().toUpperCase().trim();
            prenomEmp = prenom.getText();
            num_cni = cni.getText().trim();
            sexeEmp = sexe.getSelectedItem().toString();
            dateNaissanceEmp = daterecup;
            lieuNaissanceEmp = selectedCountry.toString();
            grpSanguinEmp = groupeSanguin.getSelectedItem().toString();
            etudeEmp = niveauEtude.getSelectedItem().toString();
            departementEmp = departement.getText();
            posteEmp = poste.getText();
            typeContratEmp = typeContrat.getSelectedItem().toString();
            salaireEmp = salaire.getText();
            embauche = daterecup1;
            telMobileEmp = telMobile.getText();
            telFixeEmp = telFixe.getText();
            emailEmp = email.getText();
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Saisir la date de naissance et la date d'embauche SVP !");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Employe().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton annuler;
    private javax.swing.JLabel back;
    private javax.swing.JPanel body;
    private javax.swing.JPanel bottom;
    private javax.swing.JFormattedTextField cni;
    private javax.swing.JPanel contact;
    private javax.swing.JLabel copyright;
    private com.toedter.calendar.JDateChooser dateEmbauche;
    private com.toedter.calendar.JDateChooser dateNaissance;
    private javax.swing.JTextField departement;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> groupeSanguin;
    private javax.swing.JPanel infoEmploi;
    private javax.swing.JPanel infoperso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Country> lieuNaissance;
    private javax.swing.JTable maTable;
    private javax.swing.JButton modifier;
    private javax.swing.JComboBox<String> niveauEtude;
    private javax.swing.JTextField nom;
    private javax.swing.JPanel operations;
    private javax.swing.JTextField poste;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField rech_nom;
    private javax.swing.JTextField rech_poste;
    private javax.swing.JPanel recherche;
    private javax.swing.JTextField salaire;
    private javax.swing.JComboBox<String> sexe;
    private javax.swing.JButton supprimer;
    private javax.swing.JFormattedTextField telFixe;
    private javax.swing.JFormattedTextField telMobile;
    private javax.swing.JPanel top;
    private javax.swing.JComboBox<String> typeContrat;
    private javax.swing.JButton vider;
    // End of variables declaration//GEN-END:variables
}
