/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package monapp;


import static BDD.Configuration.*;
import Model.Colors;
import Model.Country;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ali Abdoulkader Ali
 */

public class Promotion extends javax.swing.JFrame {

    /**
     * Creates new form Promotion
     */
    String SQL, table = "employe", nomEmp, prenomEmp, sexeEmp, dateEmbaucheEmp, etudeEmp, posteEmp, salaireEmp, postePromo, datePromo;
    String colonnes = "num_cni, nom, prenom, sexe, dateNais, etude, poste, nvposte, datepromo, salaire";
    ResultSet res;

    public Promotion() {
        initComponents();
        supprimer.setEnabled(false);
        modifier.setEnabled(false);
        top.setBackground(Colors.INSTANCE.secondaryColor());
        setLocationRelativeTo(null);
        setBackground(Colors.INSTANCE.secondaryColor());
        body.setBackground(Colors.INSTANCE.secondaryColor());
        bottom.setBackground(Colors.INSTANCE.secondaryColor());
        top.setBackground(Colors.INSTANCE.primaryColor());

        tablePromotion();
    }

    public void tablePromotion() {
        String[] colonnes = {"num_cni", "nom", "prenom", "sexe", "date_embauche", "etude", "poste", "salaire", "nvposte", "datepromo"};

        res = select(colonnes, "employe");

        maTable.setModel(DbUtils.resultSetToTableModel(res));
    }

    public void actualiser() {
        nom.setText("");
        prenom.setText("");
        sexe.setSelectedIndex(0);
        dateEmb.setCalendar(null);
        niveauEtude.setSelectedIndex(0);
        nouveau_poste.setText("");
        salaire.setText("");
        ancien_poste.setText("");
        datepromo.setCalendar(null);
        supprimer.setEnabled(false);
        modifier.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        bottom = new javax.swing.JPanel();
        infoperso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prenom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sexe = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        niveauEtude = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        ancien_poste = new javax.swing.JTextField();
        dateEmb = new com.toedter.calendar.JDateChooser();
        infoEmploi = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nouveau_poste = new javax.swing.JTextField();
        salaire = new javax.swing.JTextField();
        datepromo = new com.toedter.calendar.JDateChooser();
        operations = new javax.swing.JPanel();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        maTable = new javax.swing.JTable();
        recherche = new javax.swing.JPanel();
        rech_poste = new javax.swing.JTextField();
        rech_nom = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        body.setPreferredSize(new java.awt.Dimension(1300, 700));

        jLabel1.setBackground(new java.awt.Color(236, 204, 104));
        jLabel1.setFont(new java.awt.Font("Consolas", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(236, 204, 104));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-promotion-64.png"))); // NOI18N
        jLabel1.setText("Gestion de Promotion");
        jLabel1.setToolTipText("");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-back-48.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back)
                .addGap(441, 441, 441)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(topLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(back)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        infoperso.setBackground(Colors.INSTANCE.secondaryColor());
        infoperso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations Personnelles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(Colors.INSTANCE.textColor());
        jLabel2.setText("Nom :");

        nom.setEditable(false);
        nom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(Colors.INSTANCE.textColor()
        );
        jLabel3.setText("Prénom :");

        prenom.setEditable(false);
        prenom.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(Colors.INSTANCE.textColor());
        jLabel4.setText("Sexe :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setForeground(Colors.INSTANCE.textColor());
        jLabel5.setText("Date d'Embauche :");

        sexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir ...", "Masculin", "Féminin" }));
        sexe.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(Colors.INSTANCE.textColor());
        jLabel8.setText("Niveau D'Etude :");

        niveauEtude.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir ...", "Baccalauréat Générale", "Bac Pro", "Licence", "Master", "Doctorat", "Autre" }));
        niveauEtude.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setForeground(Colors.INSTANCE.textColor());
        jLabel16.setText("Ancien Poste :");

        ancien_poste.setEditable(false);
        ancien_poste.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        dateEmb.setEnabled(false);

        javax.swing.GroupLayout infopersoLayout = new javax.swing.GroupLayout(infoperso);
        infoperso.setLayout(infopersoLayout);
        infopersoLayout.setHorizontalGroup(
            infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopersoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(niveauEtude, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nom)
                    .addComponent(prenom)
                    .addComponent(sexe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ancien_poste)
                    .addComponent(dateEmb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        infopersoLayout.setVerticalGroup(
            infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infopersoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateEmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(niveauEtude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(infopersoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ancien_poste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        infoEmploi.setBackground(Colors.INSTANCE.secondaryColor());
        infoEmploi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informations sur l'Emploi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setForeground(Colors.INSTANCE.textColor());
        jLabel9.setText("Nouveau Poste :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setForeground(Colors.INSTANCE.textColor());
        jLabel10.setText("Date de promotion :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(Colors.INSTANCE.textColor());
        jLabel12.setText("Salaire :");

        nouveau_poste.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        salaire.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        salaire.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salaireKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout infoEmploiLayout = new javax.swing.GroupLayout(infoEmploi);
        infoEmploi.setLayout(infoEmploiLayout);
        infoEmploiLayout.setHorizontalGroup(
            infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEmploiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoEmploiLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(46, 46, 46)
                        .addComponent(nouveau_poste, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoEmploiLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(datepromo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(infoEmploiLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(99, 99, 99)
                        .addComponent(salaire, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        infoEmploiLayout.setVerticalGroup(
            infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoEmploiLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoEmploiLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(nouveau_poste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoEmploiLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel10))
                    .addGroup(infoEmploiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datepromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(infoEmploiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoEmploiLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(salaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        operations.setBackground(Colors.INSTANCE.primaryColor());
        operations.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opérations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-close-20.png"))); // NOI18N
        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });

        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-20.png"))); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cancel-20.png"))); // NOI18N
        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout operationsLayout = new javax.swing.GroupLayout(operations);
        operations.setLayout(operationsLayout);
        operationsLayout.setHorizontalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifier)
                .addGap(34, 34, 34)
                .addComponent(supprimer)
                .addGap(32, 32, 32)
                .addComponent(annuler)
                .addGap(120, 120, 120))
        );
        operationsLayout.setVerticalGroup(
            operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(operationsLayout.createSequentialGroup()
                .addGroup(operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifier)
                    .addComponent(supprimer)
                    .addComponent(annuler))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        maTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° CNI", "Nom", "Prenom", "Sexe", "DateNais", "Niveau Etude", "Ancien Poste", "Nouveau Poste", "Date de promotion", "Salaire"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        maTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maTableMouseClicked(evt);
            }
        });
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();
        jScrollPane1.setViewportView(maTable);

        recherche.setBackground(Colors.INSTANCE.primaryColor());
        recherche.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recherche", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(236, 204, 104))); // NOI18N

        rech_poste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rech_posteKeyReleased(evt);
            }
        });

        rech_nom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rech_nomKeyReleased(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setForeground(Colors.INSTANCE.textColor());
        jLabel17.setText("Nom :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel18.setForeground(Colors.INSTANCE.textColor());
        jLabel18.setText("Poste :");

        javax.swing.GroupLayout rechercheLayout = new javax.swing.GroupLayout(recherche);
        recherche.setLayout(rechercheLayout);
        rechercheLayout.setHorizontalGroup(
            rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rechercheLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rech_poste, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rech_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        rechercheLayout.setVerticalGroup(
            rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rechercheLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rech_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(rechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rech_poste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addComponent(infoperso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(infoEmploi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, 416, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bottomLayout.createSequentialGroup()
                        .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(infoEmploi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bottomLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54)
                        .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(infoperso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );

        copyright.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        copyright.setForeground(new java.awt.Color(255, 204, 102));
        copyright.setText("Copyright © 2021 | Ali Abdoulkader Ali - Helem Houmed - Aboubaker Ainan| All rights reserved");

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(copyright)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyright)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 1346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        this.dispose();
        new Bienvenue().setVisible(true);

    }//GEN-LAST:event_backMouseClicked

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed

    }//GEN-LAST:event_nomActionPerformed

    private void salaireKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaireKeyPressed
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            salaire.setEditable(false);
        } else {
            salaire.setEditable(true);
        }
    }//GEN-LAST:event_salaireKeyPressed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
         DefaultTableModel model = (DefaultTableModel) maTable.getModel();

        recuperation();

        String[] colonnes = {"nom", "prenom", "sexe", "date_embauche","etude","poste","salaire","nvposte","datepromo"};

        String[] valeurs = {nomEmp, prenomEmp, sexeEmp, dateEmbaucheEmp,etudeEmp,
            posteEmp, salaireEmp, postePromo,datePromo};

        String cni = String.valueOf(model.getValueAt(maTable.getSelectedRow(), 0));
        
        if(datepromo.getDate().after(dateEmb.getDate())){
            
            updateTable(table, colonnes, valeurs, cni);
            
        }else{
            JOptionPane.showMessageDialog(this, "La date de la promotion doit être supérieur à la date d'embauche");
        }
        
        if(datepromo.getDate() == null){
            SQL = "UPDATE employe SET datepromo=NULL";
            executionUpdate(SQL);
            tablePromotion();
        }

        tablePromotion();

    }//GEN-LAST:event_modifierActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();
        int ligne = maTable.getSelectedRow();
        String cni = String.valueOf(model.getValueAt(ligne, 0));
        if (maTable.getSelectedRowCount() == 1) {
            supprimer.setEnabled(true);
            deleteColumn(table, cni);

            if (maTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table vide !");
            }
        } else {
            supprimer.setEnabled(true);
        }

        actualiser();
        tablePromotion();
    }//GEN-LAST:event_supprimerActionPerformed

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
        actualiser();
    }//GEN-LAST:event_annulerActionPerformed

    private void maTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) maTable.getModel();

        int selectedRowIndex = maTable.getSelectedRow();
        Date date = null,date1 = null;
            supprimer.setEnabled(true);
            modifier.setEnabled(true);
        try {
      
            nom.setText(model.getValueAt(selectedRowIndex, 1).toString());
            prenom.setText(model.getValueAt(selectedRowIndex, 2).toString());
            sexe.setSelectedItem(model.getValueAt(selectedRowIndex, 3).toString());
            date = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRowIndex, 4));
            dateEmb.setDate(date);
            niveauEtude.setSelectedItem(model.getValueAt(selectedRowIndex, 5).toString());
            ancien_poste.setText(model.getValueAt(selectedRowIndex, 6).toString());
            salaire.setText(model.getValueAt(selectedRowIndex, 7).toString());
            nouveau_poste.setText(model.getValueAt(selectedRowIndex, 8).toString());
            date1 = new SimpleDateFormat("dd-MM-yyyy").parse((String) model.getValueAt(selectedRowIndex, 9));
            datepromo.setDate(date1);

            
        } catch (ParseException ex) {
            System.out.println(""); 
        }catch (NullPointerException e) {
            System.out.println(""); 
       }
        

    }//GEN-LAST:event_maTableMouseClicked

    private void rech_posteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rech_posteKeyReleased
        String poste = rech_poste.getText();
        maTable.setModel(DbUtils.resultSetToTableModel(searchByJob(table, colonnes,poste)));
    }//GEN-LAST:event_rech_posteKeyReleased

    private void rech_nomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rech_nomKeyReleased
        String nom = rech_nom.getText();
        maTable.setModel(DbUtils.resultSetToTableModel(searchByName(table,colonnes, nom)));
    }//GEN-LAST:event_rech_nomKeyReleased

    public void recuperation() {
         try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String daterecup = sdf.format(dateEmb.getDate());
            String daterecup1 = sdf.format(datepromo.getDate());
            
            nomEmp = nom.getText().toUpperCase().trim();
            prenomEmp = prenom.getText();
            sexeEmp = sexe.getSelectedItem().toString();
            dateEmbaucheEmp = daterecup;
            etudeEmp = niveauEtude.getSelectedItem().toString();
            posteEmp = ancien_poste.getText();
            postePromo = nouveau_poste.getText();
            salaireEmp = salaire.getText();
            datePromo = daterecup1;
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Saisissez bien les dates !");
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Promotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Promotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Promotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Promotion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Promotion().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ancien_poste;
    private javax.swing.JButton annuler;
    private javax.swing.JLabel back;
    private javax.swing.JPanel body;
    private javax.swing.JPanel bottom;
    private javax.swing.JLabel copyright;
    private com.toedter.calendar.JDateChooser dateEmb;
    private com.toedter.calendar.JDateChooser datepromo;
    private javax.swing.JPanel infoEmploi;
    private javax.swing.JPanel infoperso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable maTable;
    private javax.swing.JButton modifier;
    private javax.swing.JComboBox<String> niveauEtude;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nouveau_poste;
    private javax.swing.JPanel operations;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField rech_nom;
    private javax.swing.JTextField rech_poste;
    private javax.swing.JPanel recherche;
    private javax.swing.JTextField salaire;
    private javax.swing.JComboBox<String> sexe;
    private javax.swing.JButton supprimer;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
